module.exports = {
    responseCode: {
        SUCCESS: 200,
        CREATED: 201,
        BAD_REQUEST: 400,
        UNAUTHORIZED: 401,
        FORBIDDEN: 403,
        NOT_FOUND: 404,
        CONFLICT: 409,
        TOO_MANY_REQUESTS: 429,
        INTERNAL_SERVER_ERROR: 500,
    },
    responseMessage: {
        STATION_LIST: 'Station list fetched successfully',
        ERR_MSG_ISSUE_IN_STATION_LIST_API: 'Something went wrong while fetching station list',
        TRAIN_BETWEEN_STATIONS: 'Trains between stations fetched successfully',
        TRAIN_BETWEEN_STATES: 'Trains between states fetched successfully',
        TRAIN_BETWEEN_PLACES: 'Trains between places fetched successfully',
        ERR_MSG_ISSUE_IN_TRAIN_BETWEEN_API: 'Something went wrong while fetching trains between stations',
        ERR_MSG_ISSUE_IN_TRAIN_BETWEEN_STATES_API: 'Something went wrong while fetching trains between states',
        ERR_MSG_ISSUE_IN_TRAIN_BETWEEN_PLACES_API: 'Something went wrong while fetching trains between places',
        PLACE_ADD_SUCCESS: 'Place added successfully',
        PLACE_UPDATE_SUCCESS: 'Place updated successfully',
        PLACE_LIST: 'Place list fetched successfully',
        ERR_MSG_ISSUE_IN_PLACE_ADD_API: 'Something went wrong while adding place',
        ERR_MSG_ISSUE_IN_PLACE_EDIT_API: 'Something went wrong while editing place',
        ERR_MSG_ISSUE_IN_PLACE_DELETE_API: 'Something went wrong while deleting place',
        ERR_MSG_ISSUE_IN_PLACE_LIST_API: 'Something went wrong while fetching place list',
        PLACE_DELETE_SUCCESS: 'Place deleted successfully',
        ERR_OOPS_SOMETHING_WENT_WRONG: 'Oops! Something went wrong',
    },
};
