/**
 * Curated city and landmark definitions.
 *
 * The source station feed carries `state` and `district` but no city, and a
 * district is a poor stand-in for the places people actually search: "Mumbai"
 * spans two districts, "Bangalore" is stored as three, and no district is
 * called "Taj Mahal". Station codes here are validated against the DB at seed
 * time and anything unknown is reported rather than inserted.
 *
 * Order matters: the first code becomes rank 1, the primary station.
 */

const CITIES = [
  { name: "Mumbai", state: "Maharashtra", aliases: ["Bombay"], stations: ["CSMT", "LTT", "BDTS", "DR", "MMCT", "PNVL", "TNA", "KYN"] },
  { name: "Delhi", state: "Delhi", aliases: ["New Delhi", "NCR"], stations: ["NDLS", "DLI", "NZM", "ANVT", "DEE", "DEC", "SZM"] },
  { name: "Bangalore", state: "Karnataka", aliases: ["Bengaluru", "Bangaluru"], stations: ["SBC", "YPR", "KJM", "BNC", "BNCE", "BAND"] },
  { name: "Chennai", state: "Tamil Nadu", aliases: ["Madras"], stations: ["MAS", "MS", "TBM", "MSB", "AJJ"] },
  { name: "Kolkata", state: "West Bengal", aliases: ["Calcutta"], stations: ["HWH", "SDAH", "KOAA", "SRC", "BWN"] },
  { name: "Hyderabad", state: "Telangana", aliases: ["Secunderabad"], stations: ["SC", "HYB", "KCG"] },
  { name: "Pune", state: "Maharashtra", aliases: ["Poona"], stations: ["PUNE", "SVJR", "CCH", "KK"] },
  { name: "Ahmedabad", state: "Gujarat", aliases: ["Ahmadabad", "Amdavad"], stations: ["ADI", "SBIB", "MAN", "GNC"] },
  { name: "Jaipur", state: "Rajasthan", aliases: ["Pink City"], stations: ["JP", "GADJ", "DPA"] },
  { name: "Lucknow", state: "Uttar Pradesh", aliases: [], stations: ["LKO", "ASH", "LJN", "LC"] },
  { name: "Kanpur", state: "Uttar Pradesh", aliases: [], stations: ["CNB", "CPA", "GOY"] },
  { name: "Nagpur", state: "Maharashtra", aliases: [], stations: ["NGP", "AJNI"] },
  { name: "Patna", state: "Bihar", aliases: [], stations: ["PNBE", "RJPB", "PPTA", "DNR"] },
  { name: "Bhopal", state: "Madhya Pradesh", aliases: [], stations: ["BPL", "RKMP"] },
  { name: "Indore", state: "Madhya Pradesh", aliases: [], stations: ["INDB", "DWX", "LMNR"] },
  { name: "Surat", state: "Gujarat", aliases: [], stations: ["ST", "UDN", "BH"] },
  { name: "Vadodara", state: "Gujarat", aliases: ["Baroda"], stations: ["BRC", "VS", "PRTN"] },
  { name: "Varanasi", state: "Uttar Pradesh", aliases: ["Banaras", "Kashi", "Benares"], stations: ["BSB", "BNRS", "BCY", "DDU"] },
  { name: "Agra", state: "Uttar Pradesh", aliases: [], stations: ["AGC", "IDH", "AF"] },
  { name: "Amritsar", state: "Punjab", aliases: [], stations: ["ASR"] },
  { name: "Ludhiana", state: "Punjab", aliases: [], stations: ["LDH"] },
  { name: "Chandigarh", state: "Chandigarh", aliases: ["Mohali"], stations: ["CDG", "SASN"] },
  { name: "Jodhpur", state: "Rajasthan", aliases: [], stations: ["JU"] },
  { name: "Udaipur", state: "Rajasthan", aliases: [], stations: ["UDZ", "RPZ"] },
  { name: "Kota", state: "Rajasthan", aliases: [], stations: ["KOTA"] },
  { name: "Ajmer", state: "Rajasthan", aliases: [], stations: ["AII", "MDJN"] },
  { name: "Bikaner", state: "Rajasthan", aliases: [], stations: ["BKN", "LGH"] },
  { name: "Gwalior", state: "Madhya Pradesh", aliases: [], stations: ["GWL"] },
  { name: "Jabalpur", state: "Madhya Pradesh", aliases: [], stations: ["JBP", "MML"] },
  { name: "Ujjain", state: "Madhya Pradesh", aliases: [], stations: ["UJN"] },
  { name: "Prayagraj", state: "Uttar Pradesh", aliases: ["Allahabad"], stations: ["PRYJ", "PCOI", "NYN"] },
  { name: "Gorakhpur", state: "Uttar Pradesh", aliases: [], stations: ["GKP", "GKC"] },
  { name: "Bareilly", state: "Uttar Pradesh", aliases: [], stations: ["BE", "BEM"] },
  { name: "Meerut", state: "Uttar Pradesh", aliases: [], stations: ["MTC", "MUT"] },
  { name: "Ghaziabad", state: "Uttar Pradesh", aliases: [], stations: ["GZB"] },
  { name: "Mathura", state: "Uttar Pradesh", aliases: ["Vrindavan"], stations: ["MTJ", "BTSR"] },
  { name: "Jhansi", state: "Uttar Pradesh", aliases: ["Virangana Lakshmibai"], stations: ["VGLJ", "LMNR"] },
  { name: "Aligarh", state: "Uttar Pradesh", aliases: [], stations: ["ALJN"] },
  { name: "Moradabad", state: "Uttar Pradesh", aliases: [], stations: ["MB"] },
  { name: "Dehradun", state: "Uttarakhand", aliases: [], stations: ["DDN", "HW"] },
  { name: "Haridwar", state: "Uttarakhand", aliases: ["Rishikesh"], stations: ["HW", "RKSH"] },
  { name: "Jammu", state: "Jammu and Kashmir", aliases: [], stations: ["JAT", "SVDK"] },
  { name: "Shimla", state: "Himachal Pradesh", aliases: [], stations: ["SML", "KLK"] },
  { name: "Guwahati", state: "Assam", aliases: ["Gauhati"], stations: ["GHY", "KYQ"] },
  { name: "Bhubaneswar", state: "Odisha", aliases: [], stations: ["BBS", "KUR"] },
  { name: "Puri", state: "Odisha", aliases: ["Jagannath Puri"], stations: ["PURI"] },
  { name: "Cuttack", state: "Odisha", aliases: [], stations: ["CTC"] },
  { name: "Ranchi", state: "Jharkhand", aliases: [], stations: ["RNC", "HTE"] },
  { name: "Jamshedpur", state: "Jharkhand", aliases: ["Tatanagar"], stations: ["TATA"] },
  { name: "Dhanbad", state: "Jharkhand", aliases: [], stations: ["DHN"] },
  { name: "Raipur", state: "Chhattisgarh", aliases: [], stations: ["R", "DURG"] },
  { name: "Visakhapatnam", state: "Andhra Pradesh", aliases: ["Vizag"], stations: ["VSKP", "DVD"] },
  { name: "Vijayawada", state: "Andhra Pradesh", aliases: [], stations: ["BZA"] },
  { name: "Tirupati", state: "Andhra Pradesh", aliases: ["Tirumala"], stations: ["TPTY", "RU"] },
  { name: "Guntur", state: "Andhra Pradesh", aliases: [], stations: ["GNT"] },
  { name: "Warangal", state: "Telangana", aliases: [], stations: ["WL"] },
  { name: "Coimbatore", state: "Tamil Nadu", aliases: [], stations: ["CBE", "PTJ"] },
  { name: "Madurai", state: "Tamil Nadu", aliases: [], stations: ["MDU"] },
  { name: "Tiruchirappalli", state: "Tamil Nadu", aliases: ["Trichy"], stations: ["TPJ"] },
  { name: "Salem", state: "Tamil Nadu", aliases: [], stations: ["SA"] },
  { name: "Rameswaram", state: "Tamil Nadu", aliases: [], stations: ["RMM"] },
  { name: "Kochi", state: "Kerala", aliases: ["Cochin", "Ernakulam"], stations: ["ERS", "ERN", "AWY"] },
  { name: "Thiruvananthapuram", state: "Kerala", aliases: ["Trivandrum"], stations: ["TVC", "TVP"] },
  { name: "Kozhikode", state: "Kerala", aliases: ["Calicut"], stations: ["CLT"] },
  { name: "Thrissur", state: "Kerala", aliases: ["Trichur"], stations: ["TCR"] },
  { name: "Mangalore", state: "Karnataka", aliases: ["Mangaluru"], stations: ["MAJN", "MAQ"] },
  { name: "Mysore", state: "Karnataka", aliases: ["Mysuru"], stations: ["MYS"] },
  { name: "Hubli", state: "Karnataka", aliases: ["Hubballi"], stations: ["UBL"] },
  { name: "Belgaum", state: "Karnataka", aliases: ["Belagavi"], stations: ["BGM"] },
  { name: "Goa", state: "Goa", aliases: ["Panaji", "Panjim", "Vasco"], stations: ["MAO", "THVM", "VSG", "KRMI"] },
  { name: "Nashik", state: "Maharashtra", aliases: ["Nasik"], stations: ["NK", "NR"] },
  { name: "Solapur", state: "Maharashtra", aliases: [], stations: ["SUR"] },
  { name: "Kolhapur", state: "Maharashtra", aliases: [], stations: ["KOP"] },
  { name: "Rajkot", state: "Gujarat", aliases: [], stations: ["RJT"] },
  { name: "Bhavnagar", state: "Gujarat", aliases: [], stations: ["BVC"] },
  { name: "Jamnagar", state: "Gujarat", aliases: [], stations: ["JAM"] },
  { name: "Gandhinagar", state: "Gujarat", aliases: [], stations: ["GNC"] },
  { name: "Siliguri", state: "West Bengal", aliases: ["Darjeeling", "NJP"], stations: ["NJP", "SGUJ"] },
  { name: "Asansol", state: "West Bengal", aliases: [], stations: ["ASN"] },
  { name: "Kharagpur", state: "West Bengal", aliases: [], stations: ["KGP"] },
  { name: "Gaya", state: "Bihar", aliases: ["Bodh Gaya"], stations: ["GAYA"] },
  { name: "Muzaffarpur", state: "Bihar", aliases: [], stations: ["MFP"] },
  { name: "Bhagalpur", state: "Bihar", aliases: [], stations: ["BGP"] },
  { name: "Darbhanga", state: "Bihar", aliases: [], stations: ["DBG"] },
];

/** Landmarks people search for by name rather than by the station that serves them. */
const LANDMARKS = [
  { name: "Taj Mahal", state: "Uttar Pradesh", aliases: [], stations: ["AGC", "IDH"] },
  { name: "Golden Temple", state: "Punjab", aliases: ["Harmandir Sahib"], stations: ["ASR"] },
  { name: "Vaishno Devi", state: "Jammu and Kashmir", aliases: ["Katra"], stations: ["SVDK", "JAT"] },
  { name: "Tirumala Temple", state: "Andhra Pradesh", aliases: [], stations: ["TPTY", "RU"] },
  { name: "Jagannath Temple", state: "Odisha", aliases: [], stations: ["PURI"] },
  { name: "Konark", state: "Odisha", aliases: ["Sun Temple"], stations: ["PURI", "BBS"] },
  { name: "Ajanta Ellora", state: "Maharashtra", aliases: ["Ellora Caves", "Ajanta Caves"], stations: ["JL", "MMR"] },
  { name: "Hampi", state: "Karnataka", aliases: [], stations: ["HPT", "BAY"] },
  { name: "Khajuraho", state: "Madhya Pradesh", aliases: [], stations: ["KURJ"] },
  { name: "Sanchi", state: "Madhya Pradesh", aliases: [], stations: ["SCI", "BPL"] },
  { name: "Pushkar", state: "Rajasthan", aliases: [], stations: ["AII"] },
  { name: "Mount Abu", state: "Rajasthan", aliases: [], stations: ["ABR"] },
  { name: "Jaisalmer", state: "Rajasthan", aliases: [], stations: ["JSM"] },
  { name: "Ranthambore", state: "Rajasthan", aliases: [], stations: ["SWM"] },
  { name: "Bodh Gaya", state: "Bihar", aliases: [], stations: ["GAYA"] },
  { name: "Nalanda", state: "Bihar", aliases: [], stations: ["NLD", "BEHR"] },
  { name: "Shirdi", state: "Maharashtra", aliases: ["Sai Baba"], stations: ["SNSI", "KPG"] },
  { name: "Ooty", state: "Tamil Nadu", aliases: ["Udagamandalam"], stations: ["UAM", "MTP"] },
  { name: "Kanyakumari", state: "Tamil Nadu", aliases: ["Cape Comorin"], stations: ["CAPE"] },
  { name: "Munnar", state: "Kerala", aliases: [], stations: ["AWY", "ERS"] },
  { name: "Alleppey", state: "Kerala", aliases: ["Alappuzha", "Backwaters"], stations: ["ALLP"] },
  { name: "Rishikesh", state: "Uttarakhand", aliases: [], stations: ["RKSH", "HW"] },
  { name: "Nainital", state: "Uttarakhand", aliases: [], stations: ["KGM"] },
  { name: "Manali", state: "Himachal Pradesh", aliases: ["Kullu"], stations: ["UHL", "CDG"] },
  { name: "Dharamshala", state: "Himachal Pradesh", aliases: ["McLeod Ganj"], stations: ["PTKC", "PTK"] },
  { name: "Kaziranga", state: "Assam", aliases: [], stations: ["FKM", "GHY"] },
  { name: "Digha", state: "West Bengal", aliases: [], stations: ["DGHA"] },
  { name: "Puducherry", state: "Puducherry", aliases: ["Pondicherry"], stations: ["PDY"] },
];

module.exports = { CITIES, LANDMARKS };
